version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
commands:
  react-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: React Build
          command: yarn build
  install-netlify:
    steps:
      - run:
          name: Install Netlify cli
          command: sudo npm install netlify-cli -g
jobs:
  build:
    executor: node-executor
    steps:
      - react-build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - build
  deploy-prod:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - install-netlify
      - run:
          name: Netlify Deploy
          command: netlify deploy --prod --dir=/home/circleci/project/build -p
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
                - /dependabot*/
      # - test:
      #     requires:
      #       - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master